name: Vue-App-CD
on:
  push:
    branches: vue-app-release
env:
  APP_PATH: sub-app/vue-app
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v3
      # 在CD Workflow中会给每个生成的制品打上标签，而标签取值于version值
      - name: Read Package
        # 读取出来的值会放在steps.[id].outputs.value供其他步骤step读取
        id: package
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ${{ format('./{0}/package.json',env.APP_PATH) }}
          property: "version.name"
      - name: Upload Workspace to Deploy Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_TOKEN }}
          ARGS: "-avzr --delete"
          SOURCE: $APP_PATH
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ${{secrets.TARGET}}
      - name: Generate and Start Docker Container
        uses: appleboy/ssh-action@master
        env:
          Container: ${{steps.package.outputs.name}}
          Version: ${{steps.package.outputs.version}}
          Image: ${{steps.package.outputs.name}}:${{steps.package.outputs.version}}
          Network: microfe
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{ secrets.DEPLOY_TOKEN }}
          script: |
            docker ps -q --filter "name=$Container" | grep -q . && docker rm -f $Container
            cd ${{secrets.TARGET}}/$APP_PATH
            docker build -t $Image .
            docker network ls -q --filter "name=$Network" | grep -q . || docker network create microfe
            docker run -d --name $Container --network $Network $Image
