name: Vue-App-CD
on:
  push:
    branches: vue-app-release
env:
  DOC_NAME: sub-app/vue-app
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v2
      # 在CD Workflow中会给每个生成的制品打上标签，而标签取值于version值
      - name: Read Version
        # 读取出来的值会放在steps.[id].outputs.value供其他步骤step读取
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: ${{ format('./{0}/package.json',$DOC_NAME) }}
          prop_path: "version.name"
      - name: Save Secret-Key as PEM-File
        run: |
          echo "$secrets.DEPLOY_TOKEN" >> secret.pem
          cat secret.pem
      # ssh登陆部署服务器
      # - name: SSH Deploy Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{secrets.REMOTE_HOST}}
      #     username: ${{secrets.REMOTE_USER}}
      #     key: ${{secrets.DEPLOY_TOKEN}}
      #     script:
      #       - cd
