name: Vue-App-CD
on:
  push:
    branches: vue-app-release
env:
  DOC_NAME: sub-app/vue-app
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v2
      # 在CD Workflow中会给每个生成的制品打上标签，而标签取值于version值
      - name: Read Version
        # 读取出来的值会放在steps.[id].outputs.value供其他步骤step读取
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ${{ format('./{0}/package.json',env.DOC_NAME) }}
          property: "version.name"
      - name: Upload Workspace to Deploy Server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_TOKEN }}
          ARGS: "-avzr --delete"
          SOURCE: $DOC_NAME
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: "/root/project"
      # ssh登陆部署服务器
      # - name: SSH Deploy Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{secrets.REMOTE_HOST}}
      #     username: ${{secrets.REMOTE_USER}}
      #     key: ${{secrets.DEPLOY_TOKEN}}
      #     script:
      #       - cd
